version: '3.9'

services:
  db:
    image: postgres
    container_name: projet-annuel-postgres
    volumes:
      - postgres-data:/var/lib/projet-annuel/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

volumes:
  postgres-data: {}
